In [3]:
import numpy as np

natural_numbers = np.arange(1, 11)
print(natural_numbers)

[ 1  2  3  4  5  6  7  8  9 10]


In [30]:
# matr = np.array([[0,0,0],[0,0,0],[0,0,0]], dtype = int)
matr = np.zeros((3, 3))
print(matr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
matr = np.random.randint(1, 11, size=(5, 5))
print(matr)

[[ 7 10 10  5 10]
 [10  2  5  7  2]
 [ 5  8  2  4  5]
 [ 8  4  3  3  1]
 [ 2  1  1  4  3]]


In [8]:
matr = np.random.rand(4, 4)
print(matr)

[[0.36756065 0.32532341 0.77789992 0.57227734]
 [0.79613125 0.76487867 0.49713434 0.75593148]
 [0.34567133 0.75455411 0.77099946 0.86341041]
 [0.54460478 0.41400474 0.13875774 0.14806056]]


In [13]:
a1 = np.random.randint(1,11, size=(5))
a2 = np.random.randint(1,11, size=(5))

a3 = a1 + a2
np.set_printoptions(precision=2, suppress=True)

print("Array 1:\n", a1)
print("Array 2:\n", a2)
print("Sum of Array 1 and 2 (Array 3):\n", a3)
a3 = a1 - a2
print("Sub of Array 1 and 2 (Array 3):\n", a3)
a3 = a1 * a2
print("Mult of Array 1 and 2 (Array 3):\n", a3)

Array 1:
 [8 4 1 9 5]
Array 2:
 [ 7  9  2 10  8]
Sum of Array 1 and 2 (Array 3):
 [15 13  3 19 13]
Sub of Array 1 and 2 (Array 3):
 [ 1 -5 -1 -1 -3]
Mult of Array 1 and 2 (Array 3):
 [56 36  2 90 40]


In [15]:
v1 = np.random.randint(1,11, size=(7))
v2 = np.random.randint(1,11, size=(7))

v3 = np.dot(v1, v2)

print("Scalar Product:", v3)

Scalar Product: 170


In [17]:
m1 = np.random.randint(1,11, size=(2,2))
m2 = np.random.randint(1,11, size=(2,3))

m3 = np.dot(m1,m2)

print("Matrix 1:\n", m1)
print("Matrix 2:\n", m2)
print("Mult of Matrix 1 and 2 (Matrix 3):\n", a3)

Matrix 1:
 [[6 1]
 [9 6]]
Matrix 2:
 [[1 7 5]
 [8 9 5]]
Mult of Matrix 1 and 2 (Matrix 3):
 [56 36  2 90 40]


In [20]:
mat = np.random.randint(1,11, size=(3,3))

mat_inv = np.linalg.inv(mat)
print('Matrix:',mat)
print('Invert matrix :', mat_inv)

Matrix: [[ 7  4  2]
 [ 9 10  6]
 [ 7  5  4]]
Invert matrix : [[ 0.23 -0.14  0.09]
 [ 0.14  0.32 -0.55]
 [-0.57 -0.16  0.77]]


In [21]:
mat = np.random.rand(4, 4)

mat_t = mat.T

print('Matrix:',mat)
print('Transpose matrix :', mat_t)

Matrix: [[0.75 0.02 0.97 0.46]
 [0.03 0.34 0.72 0.41]
 [0.22 0.85 0.86 0.55]
 [0.48 0.37 0.79 0.88]]
Transpose matrix : [[0.75 0.03 0.22 0.48]
 [0.02 0.34 0.85 0.37]
 [0.97 0.72 0.86 0.79]
 [0.46 0.41 0.55 0.88]]


In [23]:
m = np.random.randint(1, 11, size=(3, 4))
v = np.random.randint(1, 11, size=4)

r = np.dot(m, v)

print("Matrix:\n", m)
print("Vector:\n", v)
print("Result of Multiplication:\n", r)


Matrix:
 [[10  3  4  4]
 [ 2  4  6  3]
 [ 7 10  7  5]]
Vector:
 [5 6 2 8]
Result of Multiplication:
 [108  70 149]


In [24]:
m = np.random.rand(2, 3)
v = np.random.rand(3)

r = np.dot(m, v)

print("Matrix:\n", m)
print("Vector:\n", v)
print("Result of Multiplication:\n", r)

Matrix:
 [[0.55 0.43 0.65]
 [0.26 0.69 0.27]]
Vector:
 [0.46 0.3  0.79]
Result of Multiplication:
 [0.9  0.54]


In [26]:
m1 = np.random.randint(1, 11, size=(2, 2))
m2 = np.random.randint(1, 11, size=(2, 2))

print("Matrix:\n", m1)
print("Vector:\n", m2)
print("Result of Multiplication element to element:\n", m1 * m2)

Matrix:
 [[5 2]
 [2 7]]
Vector:
 [[8 1]
 [3 1]]
Result of Multiplication element to element:
 [[40  2]
 [ 6  7]]


In [27]:
m1 = np.random.randint(1, 11, size=(2, 2))
m2 = np.random.randint(1, 11, size=(2, 2))

print("Matrix:\n", m1)
print("Vector:\n", m2)
print("Result of Multiplication:\n", np.dot(m1, m2))

Matrix:
 [[9 1]
 [4 9]]
Vector:
 [[3 6]
 [4 6]]
Result of Multiplication:
 [[31 60]
 [48 78]]


In [29]:
matrix = np.random.randint(1, 101, size=(5, 5))
sum_of_elements = np.sum(matrix)
print("Matrix:\n", matrix)
print("Sum of all elements:", sum_of_elements)

Matrix:
 [[58 90 92 66 42]
 [86 55 78 70 81]
 [61 20  2 36 48]
 [14 67 39 76  7]
 [69  7 15 46 35]]
Sum of all elements: 1260


In [31]:
matrix1 = np.random.randint(1, 11, size=(4, 4))
matrix2 = np.random.randint(1, 11, size=(4, 4))

difference = matrix1 - matrix2

print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)
print("Difference (Matrix 1 - Matrix 2):\n", difference)

Matrix 1:
 [[ 2  4  9  1]
 [ 2  9 10  4]
 [ 3  6  7  1]
 [ 3  9  9  5]]
Matrix 2:
 [[ 4  2  6  2]
 [ 6  9  1 10]
 [ 4  5  3  4]
 [ 3  8  6  9]]
Difference (Matrix 1 - Matrix 2):
 [[-2  2  3 -1]
 [-4  0  9 -6]
 [-1  1  4 -3]
 [ 0  1  3 -4]]


In [32]:

matrix = np.random.rand(3, 3)
row_sums = np.sum(matrix, axis=1)
column_vector = row_sums.reshape(-1, 1)

print("Matrix:\n", matrix)
print("Column Vector (Sum of each row):\n", column_vector)

Matrix:
 [[0.37 0.48 0.14]
 [0.28 0.19 0.82]
 [0.4  0.6  0.01]]
Column Vector (Sum of each row):
 [[0.99]
 [1.29]
 [1.01]]


In [33]:
matrix = np.random.randint(1, 11, size=(3, 4))
squared_matrix = np.square(matrix)

print("Original Matrix:\n", matrix)
print("Squared Matrix:\n", squared_matrix)

Original Matrix:
 [[ 4  3 10  7]
 [ 5  2  4  7]
 [ 7  1  1  8]]
Squared Matrix:
 [[ 16   9 100  49]
 [ 25   4  16  49]
 [ 49   1   1  64]]


In [34]:
vector = np.random.randint(1, 51, size=4)
sqrt_vector = np.sqrt(vector)

print("Original Vector:", vector)
print("Square Root Vector:", sqrt_vector)

Original Vector: [ 6 45 44 17]
Square Root Vector: [2.45 6.71 6.63 4.12]
